// Code generated by protoc-gen-go.
// source: reading-list.proto
// DO NOT EDIT!

/*
Package readinglist is a generated protocol buffer package.

It is generated from these files:
	reading-list.proto

It has these top-level messages:
	PutLinkProtoJSONRequest
	GetListProtoJSONRequest
	Link
	LinkRequest
	Links
	Message
*/
package readinglist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutLinkProtoJSONRequest struct {
	// The transport to respond with (Protobuf or JSON)
	ProtoJSON string `protobuf:"bytes,1,opt,name=protoJSON" json:"protoJSON,omitempty"`
	// The Link to save
	Request *LinkRequest `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	// value from Google, populated by middleware
	UserID string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *PutLinkProtoJSONRequest) Reset()                    { *m = PutLinkProtoJSONRequest{} }
func (m *PutLinkProtoJSONRequest) String() string            { return proto.CompactTextString(m) }
func (*PutLinkProtoJSONRequest) ProtoMessage()               {}
func (*PutLinkProtoJSONRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutLinkProtoJSONRequest) GetProtoJSON() string {
	if m != nil {
		return m.ProtoJSON
	}
	return ""
}

func (m *PutLinkProtoJSONRequest) GetRequest() *LinkRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PutLinkProtoJSONRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetListProtoJSONRequest struct {
	// The limit of links to fetch
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// The transport to respond with (Protobuf or JSON)
	ProtoJSON string `protobuf:"bytes,1,opt,name=protoJSON" json:"protoJSON,omitempty"`
	// value from Google, populated by middleware
	UserID string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetListProtoJSONRequest) Reset()                    { *m = GetListProtoJSONRequest{} }
func (m *GetListProtoJSONRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListProtoJSONRequest) ProtoMessage()               {}
func (*GetListProtoJSONRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetListProtoJSONRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListProtoJSONRequest) GetProtoJSON() string {
	if m != nil {
		return m.ProtoJSON
	}
	return ""
}

func (m *GetListProtoJSONRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Link struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *Link) Reset()                    { *m = Link{} }
func (m *Link) String() string            { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()               {}
func (*Link) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Link) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type LinkRequest struct {
	// True to remove this link from the user's list.
	Delete bool  `protobuf:"varint,1,opt,name=delete" json:"delete,omitempty"`
	Link   *Link `protobuf:"bytes,2,opt,name=link" json:"link,omitempty"`
}

func (m *LinkRequest) Reset()                    { *m = LinkRequest{} }
func (m *LinkRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()               {}
func (*LinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LinkRequest) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

func (m *LinkRequest) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type Links struct {
	Links []*Link `protobuf:"bytes,1,rep,name=links" json:"links,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Links) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

type Message struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PutLinkProtoJSONRequest)(nil), "readinglist.PutLinkProtoJSONRequest")
	proto.RegisterType((*GetListProtoJSONRequest)(nil), "readinglist.GetListProtoJSONRequest")
	proto.RegisterType((*Link)(nil), "readinglist.Link")
	proto.RegisterType((*LinkRequest)(nil), "readinglist.LinkRequest")
	proto.RegisterType((*Links)(nil), "readinglist.Links")
	proto.RegisterType((*Message)(nil), "readinglist.Message")
}

func init() { proto.RegisterFile("reading-list.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0xdd, 0x4e, 0x32, 0x31,
	0x10, 0xa5, 0xdf, 0xf2, 0xf3, 0x31, 0x7b, 0x83, 0x13, 0x22, 0x0d, 0xf1, 0x82, 0x54, 0x8d, 0xdc,
	0x48, 0xcc, 0xfa, 0x0a, 0x26, 0x46, 0x83, 0x48, 0xca, 0x13, 0xa0, 0x4c, 0x48, 0xc3, 0xb2, 0x60,
	0xdb, 0xf5, 0x05, 0x7c, 0x27, 0x9f, 0xcf, 0xb4, 0x5b, 0x02, 0xec, 0x4a, 0xbc, 0xeb, 0x99, 0x39,
	0x73, 0xe6, 0x4c, 0x0f, 0xa0, 0xa6, 0xf9, 0x42, 0x65, 0xcb, 0xdb, 0x54, 0x19, 0x3b, 0xda, 0xea,
	0x8d, 0xdd, 0x60, 0x1c, 0x6a, 0xae, 0x24, 0xbe, 0x18, 0xf4, 0xa6, 0xb9, 0x1d, 0xab, 0x6c, 0x35,
	0x75, 0xdd, 0xe7, 0xd9, 0xeb, 0x44, 0xd2, 0x47, 0x4e, 0xc6, 0xe2, 0x05, 0xb4, 0xb7, 0xbb, 0x1a,
	0x67, 0x03, 0x36, 0x6c, 0xcb, 0x7d, 0x01, 0x13, 0x68, 0xe9, 0x82, 0xc8, 0xa3, 0x01, 0x1b, 0xc6,
	0x09, 0x1f, 0x1d, 0x08, 0x8f, 0x9c, 0x62, 0x10, 0x92, 0x3b, 0x22, 0x9e, 0x43, 0x33, 0x37, 0xa4,
	0x9f, 0x1e, 0xf8, 0x3f, 0x2f, 0x17, 0x90, 0x20, 0xe8, 0x3d, 0x92, 0x1d, 0x2b, 0x63, 0x2b, 0x26,
	0xba, 0xd0, 0x48, 0xd5, 0x5a, 0x59, 0x3f, 0xd1, 0x90, 0x05, 0xf8, 0xc3, 0xda, 0x7e, 0x4d, 0x74,
	0xb4, 0x86, 0x43, 0xdd, 0xd9, 0xc2, 0x0e, 0x44, 0xb9, 0x4e, 0xc3, 0x9c, 0x7b, 0x8a, 0x31, 0xc4,
	0x07, 0x86, 0x9d, 0xc0, 0x82, 0x52, 0xb2, 0xe4, 0x39, 0xff, 0x65, 0x40, 0x78, 0x0d, 0xf5, 0x54,
	0x65, 0x2b, 0xef, 0x25, 0x4e, 0xce, 0xaa, 0x07, 0xfb, 0xb6, 0xb8, 0x83, 0x86, 0x43, 0x06, 0x6f,
	0x9c, 0xf9, 0x6c, 0x65, 0x38, 0x1b, 0x44, 0xbf, 0x0f, 0x14, 0x7d, 0x71, 0x09, 0xad, 0x17, 0x32,
	0x66, 0xbe, 0x24, 0xe4, 0xd0, 0x5a, 0x17, 0xcf, 0x60, 0x70, 0x07, 0x93, 0x6f, 0x06, 0x28, 0x0b,
	0x01, 0xf7, 0x55, 0x33, 0xd2, 0x9f, 0xea, 0x9d, 0x70, 0x0a, 0x9d, 0x72, 0x82, 0x78, 0x75, 0xb4,
	0xe9, 0x44, 0xc0, 0xfd, 0xee, 0x11, 0x2b, 0x18, 0x10, 0x35, 0x9c, 0x40, 0xa7, 0x1c, 0x47, 0x49,
	0xf1, 0x44, 0x5a, 0x7d, 0xac, 0x5c, 0x68, 0x44, 0xed, 0xad, 0xe9, 0xa3, 0xb9, 0xff, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0x44, 0x60, 0x3a, 0x8e, 0x02, 0x00, 0x00,
}
